catalog/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("i18n/", include("django.conf.urls.i18n")),
    path("books/", views.BookListView.as_view(), name="books"),
    path(
        "bookinst-manage/",
        views.LoanedBooksManageListView.as_view(),
        name="bookinst-manage",
    ),
    path(
        "book/<uuid:pk>/renew/", views.renew_book_librarian, name="renew-book-librarian"
    ),
    path("book/<int:pk>", views.BookDetailView.as_view(), name="book-detail"),
    path("mybooks/", views.LoanedBooksByUserListView.as_view(), name="my-borrowed"),
    path("authors/", views.AuthorListView.as_view(), name="authors"),
    path("author/<int:pk>", views.AuthorDetailView.as_view(), name="author-detail"),
    path("author/create/", views.AuthorCreate.as_view(), name="author-create"),
    path("author/<int:pk>/update/", views.AuthorUpdate.as_view(), name="author-update"),
    path("author/<int:pk>/delete/", views.AuthorDelete.as_view(), name="author-delete"),
]

locallibrary/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView
from django.conf.urls.static import static
from locallibrary import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("catalog/", include("catalog.urls")),
    path("", RedirectView.as_view(url="catalog/")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

# accounts/ login/ [name='login']
# accounts/ logout/ [name='logout']
# accounts/ password_change/ [name='password_change']
# accounts/ password_change/done/ [name='password_change_done']
# accounts/ password_reset/ [name='password_reset']
# accounts/ password_reset/done/ [name='password_reset_done']
# accounts/ reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/ reset/done/ [name='password_reset_complete']

catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
import uuid
from datetime import date
from catalog.constant import LOAN_STATUS


class Genre(models.Model):
    """Model representing a book genre."""

    name = models.CharField(
        max_length=200, help_text="Enter a book genre (e.g.Science Fiction)"
    )

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""

    title = models.CharField(max_length=200)
    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)
    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book"
    )
    isbn = models.CharField(
        "ISBN",
        max_length=13,
        unique=True,
        help_text='13 Character <ahref="https://www.isbn-international.org/content/what-isbn">ISBN number</a>',
    )
    genre = models.ManyToManyField(Genre, help_text="Select a genre for this book")

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the url to access a detail record for this book."""
        return reverse("book-detail", args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ", ".join(genre.name for genre in self.genre.all()[:3])

    display_genre.short_description = "Genre"


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""

    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        help_text="Unique ID for this particular book across whole library",
    )
    book = models.ForeignKey("Book", on_delete=models.CASCADE)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default="m",
        help_text="Book availability",
    )

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    class Meta:
        ordering = ["due_back"]
        permissions = (
            ("view_list_on_loan", "Get all book on loan"),
            ("can_mark_returned", "Can mark returned book"),
        )

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.id} ({self.book.title})"


class Author(models.Model):
    """Model representing an author."""

    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField("Died", null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse("author-detail", args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f"{self.last_name}, {self.first_name}"

catalog/forms.py
import datetime
from django import forms
from django.forms import ModelForm
from bootstrap_datepicker_plus.widgets import DatePickerInput
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from catalog.models import BookInstance


class RenewBookModelForm(ModelForm):
    def clean_due_back(self):
        data = self.cleaned_data["due_back"]

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_("Invalid date - renewal in past"))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_("Invalid date - renewal more than 4 weeks ahead"))
        # Remember to always return the cleaned data.
        return data

    class Meta:
        model = BookInstance
        fields = ["due_back"]
        labels = {"due_back": _("Renewal date")}
        help_texts = {
            "due_back": _("Enter a date between now and 4 weeks (default 3).")
        }
        widgets = {"due_back": DatePickerInput()}

catalog/views.py
from django.utils.translation import gettext
from django.http import Http404
from catalog.models import Book, Author, BookInstance
from django.views import generic
import datetime
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from catalog.forms import RenewBookModelForm
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy, reverse

# Create your views here.


def index(request):
    """View function for home page of site."""
    # Generate counts of some of the main objects
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact="a").count()
    num_authors = Author.objects.count()
    num_visits = request.session.get("num_visits", 1)
    request.session["num_visits"] = num_visits + 1
    age_cookie = request.session.get_session_cookie_age()
    context = {
        "num_books": num_books,
        "num_instances": num_instances,
        "num_instances_available": num_instances_available,
        "num_authors": num_authors,
        "num_visits": num_visits,
        "age_cookie": datetime.timedelta(seconds=age_cookie),
    }

    return render(request, "index.html", context=context)


class BookListView(generic.ListView):
    model = Book
    # your own name for the list as a template variable
    paginate_by = 10

    def get_queryset(self):
        return Book.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BookListView, self).get_context_data(**kwargs)
        return context


class BookDetailView(generic.DetailView):
    model = Book

    def book_detail_view(request, primary_key):
        try:
            book = Book.objects.get(pk=primary_key)
        except Book.DoesNotExist:
            raise Http404(gettext("Book does not exist"))

        return render(request, "catalog/book_detail.html", context={"book": book})

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(BookDetailView, self).get_context_data(**kwargs)
        context["book_instance"] = context["book"].bookinstance_set.order_by(
            "-due_back"
        )
        return context


class AuthorListView(generic.ListView):
    model = Author
    # your own name for the list as a template variable
    paginate_by = 10

    def get_queryset(self):
        return Author.objects.all()

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get the context
        context = super(AuthorListView, self).get_context_data(**kwargs)
        # # Create any data and add it to the context
        # context["some_data"] = "This is just some data"
        return context


class AuthorDetailView(generic.DetailView):
    model = Author

    def author_detail_view(request, primary_key):
        try:
            author = Author.objects.get(pk=primary_key).select_related("book")
        except Author.DoesNotExist:
            raise Http404(gettext("Author does not exist"))

        return render(request, "author/author_detail.html", context={"author": author})

    def get_context_data(self, **kwargs):
        context = super(AuthorDetailView, self).get_context_data(**kwargs)
        context["books"] = context["author"].book_set.all()
        return context


class LoanedBooksByUserListView(LoginRequiredMixin, generic.ListView):
    """Generic class-based view listing books on loan to current user."""

    model = BookInstance
    template_name = "catalog/bookinstance_list_borrowed_user.html"
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.filter(borrower=self.request.user)
            .filter(status__exact="o")
            .order_by("due_back")
        )


class LoanedBooksManageListView(
    LoginRequiredMixin, PermissionRequiredMixin, generic.ListView
):
    """Generic class-based view listing books on loan to current user."""

    model = BookInstance
    permission_required = "catalog.view_list_on_loan"
    template_name = "catalog/bookinstance_manage.html"
    paginate_by = 10

    def get_queryset(self):
        return (
            BookInstance.objects.all()
            .filter(status__exact="o")
            .order_by("-due_back")
            .select_related("borrower")
        )


@login_required
@permission_required("catalog.can_mark_returned", raise_exception=True)
def renew_book_librarian(request, pk):
    book_instance = get_object_or_404(BookInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == "POST":
        # Create a form instance and populate it with data from the request (binding):
        form = RenewBookModelForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            book_instance.due_back = form.cleaned_data["due_back"]
            book_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse("bookinst-manage"))

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewBookModelForm(initial={"due_back": proposed_renewal_date})

    context = {
        "form": form,
        "book_instance": book_instance,
    }

    return render(request, "catalog/book_renew_librarian.html", context)


class AuthorCreate(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Author
    permission_required = "catalog.add_author"
    fields = ["first_name", "last_name", "date_of_birth", "date_of_death"]
    initial = {"date_of_death": "11/06/2020"}


class AuthorUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Author
    permission_required = "catalog.change_author"

    fields = "__all__"


class AuthorDelete(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Author
    permission_required = "catalog.delete_author"
    success_url = reverse_lazy("authors")

catalog/templates/catalog/author_confirm_delete.html
{% extends "base_generic.html" %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Delete Author" %}</h1>
    <p>{% trans "Are you sure you want to delete the author:" %} {{ author }}?</p>
    <form action="" method="post">
        {% csrf_token %}
        <input type="submit" value="{% trans 'Yes, delete.' %}" />
    </form>
{% endblock %}

catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}
{% block content %}
  {% load i18n %}
  <h1>{% trans "Author:" %} {{ author.first_name }} {{ author.last_name }}</h1>
  <!-- author detail link not yet defined -->
  <p>
    <strong>{% trans "Birthday:" %}</strong> {{ author.date_of_birth }}
  </p>
  <div>
    <h4>Book</h4>
    {% for book in books %}
      <hr />
      <div>{{ book.title }}</div>
    {% endfor %}
  </div>
  <div class="d-flex gap-1">
    {% if perms.catalog.change_author %}
      <a class="blue" href="{% url 'author-update' author.id %}">{% trans "Update" %}</a>
    {% endif %}
    {% if perms.catalog.delete_author %}
      <a class="red" href="{% url 'author-delete' author.id %}">{% trans "Delete" %}</a>
    {% endif %}
  </div>
{% endblock %}

catalog/templates/catalog/author_form.html
{% extends "base_generic.html" %}
{% block content %}
    {% load i18n %}
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="{% trans 'Submit' %}" />
    </form>
{% endblock %}

catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
{% block content %}
  {% load i18n %}
  <h1>{% trans "Author List" %}</h1>
  {% if author_list %}
    <ul class="pl-40">
      {% for author in author_list %}
        <li>
          <a href="{{ author.get_absolute_url }}">{{ author.first_name }} {{ author.last_name }}</a>
          <!-- ({{book.author}}) -->
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>{% trans "There are no authors in the library." %}</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_detail.html
{% extends "base_generic.html" %}
{% block content %}
  {% load i18n %}
  <h1>{% trans "Title" %}: {{ book.title }}</h1>
  <p>
    <strong>{% trans "Author:" %}</strong> <a href="">{{ book.author }}</a>
  </p>
  <!-- author detail link not yet defined -->
  <p>
    <strong>{% trans "Summary:" %}</strong> {{ book.summary }}
  </p>
  <p>
    <strong>{% trans "ISBN:" %}</strong> {{ book.isbn }}
  </p>
  <p>
    <strong>{% trans "Language:" %}</strong> {{ book.language }}
  </p>
  <p>
    <strong>{% trans "Genre:" %}</strong> {{ book.genre.all|join:", " }}
  </p>
  <div class="mlt-20 ">
    <h4>{% trans "Copies" %}</h4>
    {% for copy in book_instance %}
      <hr />
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p>
          <strong>{% trans "Due to be returned:" %}</strong> {{ copy.due_back }}
        </p>
      {% endif %}
      <p>
        <strong>{% trans "Imprint:" %}</strong> {{ copy.imprint }}
      </p>
      <p class="text-muted">
        <strong>Id:</strong> {{ copy.id }}
      </p>
    {% endfor %}
  </div>
{% endblock content %}

catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}" />
{% block content %}
  {% load i18n %}
  <h1>{% trans "Book List" %}</h1>
  {% if book_list %}
    <ul class="pl-40">
      {% for book in book_list %}
        <li>
          <a href="{{ book.get_absolute_url }}">{{ book.title }}</a>
          ({{ book.author }})
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>{% trans "There are no books in the library." %}</p>
  {% endif %}
{% endblock %}

catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}
{% block content %}
    {% load i18n %}
    {{ form.media }}
    <h1>{% trans "Renew:" %} {{ book_instance.book.title }}</h1>
    <p>{% trans "Borrower:" %} {{ book_instance.borrower }}</p>
    <p {% if book_instance.is_overdue %}class="text-danger"{% endif %}>
        {% trans "Due date: " %}{{ book_instance.due_back }}
    </p>
    <form action="" method="post">
        {% csrf_token %}
        <table>
            {{ form }}
        </table>
        <input type="submit" value="{% trans 'Submit' %}">
    </form>
{% endblock %}

catalog/templates/catalog/bookinstance_list_borrowed_user.html
{% extends "base_generic.html" %}
{% block content %}
    {% load i18n %}
    <h1>{% trans "Books on loan" %}s</h1>
    {% if bookinstance_list %}
        <ul>
            {% for bookinst in bookinstance_list %}
                <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                    <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>{% trans "There are no books borrowed." %}</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/bookinstance_manage.html
{% extends "base_generic.html" %}
{% block content %}
    {% load i18n %}
    <h1>{% trans "Borrowed books" %}</h1>
    {% if bookinstance_list %}
        <ul>
            {% for bookinst in bookinstance_list %}
                <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
                    <a href="{% url 'book-detail' bookinst.book.pk %}">{{ bookinst.book.title }}</a> ({{ bookinst.due_back }})-{{ bookinst.borrower.last_name }} {{ bookinst.borrower.first_name }}
                    {% if perms.catalog.can_mark_returned %}
                        - <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>
                    {% endif %}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>{% trans "There are no books borrowed." %}</p>
    {% endif %}
{% endblock %}